### PR TITLE
update versions

### PR DESCRIPTION
**Pull request by mrd**
Hi - is it alright to merge this change upgrading the dependency to newer versions of containers / HUnit, and then upload it to hackage?

Thanks.

### CODE REVIEW

**Comment by mtesseract** [comment]
Hi,

thanks for your contribution!
Of course we can improve the version bounds.
But why are you also increasing the lower bounds of the dependencies?

What do you think about only increasing the upper bounds and adding a version bump to the package itself?

Moritz

**Comment by KirillErofeev** [comment]
Hi,

since there is no answer from **mrd**, I think it will be fine just change only the upper bounds and upload it to hackage, so that library can be used without any difficulties.

**Comment by mtesseract** [comment]
Replaced in favour of #6

**Comment by mrd** [comment]
Thanks, sorry my notifications are screwy.

**Pull request closed without merging**
